import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { CustomersComponent } from './customers.component';

const routes: Routes = [

  {path:'customers', component: CustomersComponent}, //uses the path from the app-routing redirectTo module and loads the customerComponent
];
//this autogenerated module allows us to use routing. 

@NgModule({
  imports: [RouterModule.forChild(routes)], //forChild is used to add these routes to the forRoot ones from the app-routing modules
  exports: [RouterModule] //makes the bucket of tools available to any other components. Exports = making something public
})
export class CustomersRoutingModule {


 } //this is the name of the module imported
